config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: "users/sessions",registrations: "users/registrations"}
  resources :responses

  resources :topics

	root :to => "topics#index"

end

app/models/response.rb
class Response < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	mount_uploader :picture, PictureUploader
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :responses
	belongs_to :user
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :topics
	has_many :responses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception #残しといていいものか?

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_in) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_response, only: [:show, :edit, :update, :destroy]

  # GET /responses
  # GET /responses.json
  def index
    @responses = Response.all
  end

  # GET /responses/1
  # GET /responses/1.json
  def show
  end

  # GET /responses/new
  def new
    @response = Response.new
		@response.topic_id = params[:topic_id]
		@response.user_id = current_user.id if current_user
  end

  # GET /responses/1/edit
  def edit
  end

  # POST /responses
  # POST /responses.json
  def create
    @response = Response.new(response_params)

		if @response.save
			redirect_to('/topics/' + @response.topic_id.to_s)
		else
			respond_to do |format|
				format.html { render :new }
				format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responses/1
  # PATCH/PUT /responses/1.json
  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
        format.json { render :show, status: :ok, location: @response }
      else
        format.html { render :edit }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.json
  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_response
      @response = Response.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def response_params
      params.require(:response).permit(:topic_id, :user_id, :body, :picture)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
		@topic.user_id = current_user.id if current_user
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :user_id, :body, :url, :picture)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	
	<div id="wrap">
		<%= f.hidden_field :topic_id %>
		<%= f.hidden_field :user_id %>
		<h3>回答者:<%= current_user ? current_user.name : "名無しさん" %></h3>
	  <div class="field">
			画像 <br>
			<%= f.file_field :picture %>
	  </div>
	  <div class="field">
			返信 <br>
			<%= f.text_area :body, :class => "form-control" %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	</div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.topic_id %></td>
        <td><%= response.user_id %></td>
        <td><%= response.body %></td>
				<td><%= image_tag(response.picture_url) if response.picture.present? %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @response.topic_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @response.user_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @response.body %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="wrap">
		
		<%= f.hidden_field :user_id %>
		<h3>質問者:<%= current_user ? current_user.name : "名無しさん" %></h3>
  	<div class="field">
  	  <%= f.label :title %><br>
  	<%= f.text_field :title, :class => "form-control" %>
  	</div>
  	<div class="field">
		<%= f.label :picture %> <br>
  	<%= f.file_field :picture %>
  	</div>
  	<div class="field">
			<div id="slide-switch"><span id="slide-rotate">▼</span><%= f.label :body %><br></div>
			<%= f.text_area :body, :id => "slide-content", :class => "form-control" %>
  	</div>
  	<div class="actions">
  	  <%= f.submit %>
  	</div>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>
<div id="wrap" class="row">
	<div id="topic" class="col-md-8">
		<div class="conteiner">
			<table class="table">
				<thead>
					<tr>
						<th>トピック一覧</th>
						<th>レス数</th>
					</tr>
				</thead>
				<tbody>
					<% @topics.each do |topic| %>
						<tr>
							<td class="titles">
								<% if topic.body != "" %>
									<%= link_to topic.title, topic, :class => 'tooltip', :title => topic.body %></td>
								<% else %>
									<%= link_to topic.title, topic %></td>
								<% end %>
							<td><span class="badge"><%= topic.responses.length %></span></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>

	<!-- サイドバー -->
	<div class="col-md-3 col-md-offset-1 sidebar">
		<%= current_user.name if current_user %><br>
		<%= link_to 'New Topic', new_topic_path, :class => 'btn btn-primary'%><br>

		<% if user_signed_in? %>
			<%= link_to 'sign out', destroy_user_session_path, method: :delete %><br>
		<% else %>
			<%= link_to 'sign in', new_user_session_path %><br>
		<% end %>
	</div>
</div>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div id="wrap" class="row">
	<h1><%= @topic.title %></h1>
	<div id="topic" class="col-md-8">

    <!-- 質問者の投稿 -->
		<h2 class="user"><%= User.find(@topic.user_id).name if @topic.user_id.present?%></h2>
		<div class="topic-contents">
			<%= @topic.body %><br>
			<div class="pictures">
				<%= image_tag(@topic.picture_url) if @topic.picture.present? %><br>
			</div>
		</div>

		<div style="text-align:center">
		<%= link_to 'この質問に回答する', new_response_path(topic_id:@topic.id), :class => 'btn btn-primary' %>
		</div>

		<h2> この質問に寄せられた回答<span class="badge"><%= @topic.responses.length %></span></h2>
		<!-- 回答者の投稿 -->
		<% @topic.responses.each do |response| %> 
			<h2 class="user"><%= "名無しさん" if ! response.user_id.present? %><%= User.find(response.user_id).name if response.user_id.present? %></h2> 
			<div class="<%= current_user ? current_user.id == response.user_id ? "users-contents" : "responses-contents" : "responses-contents" %>">
				<%= response.body %> <br>
				<%= image_tag(response.picture_url, :class => 'topics_img') if response.picture.present? %>
			</div>
		<% end %>
	<%= link_to 'Back', topics_path, :class => 'btn btn-primary' %>
	</div>

	<!-- サイドバー -->
	<div class="col-md-3 col-md-offset-1 sidebar">
		<%= link_to 'この質問に回答する', new_response_path(topic_id:@topic.id), :class => 'btn btn-primary' %>
	</div>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>